default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("MYSQL_MAX_THREADS") { 50 } %>

development:
  <<: *default
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>

test:
  <<: *default
  url: <%= ENV['TEST_DATABASE_URL'] %>

production:
  <<: *default
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>